### ISSUE TITLE
fix m4 include path, be friendlier, fix distcheck, avoid a libtool stupidity

### ISSUE THREAD

**Issue by nigoroll** [Dridi/vcdk#2]
@Dridi based on our IRC discussion, I would appreciate if you considered these changes for inclusion in vcdk. Let me know if you want a PR, I would just like to get your feedback first.

https://github.com/nigoroll/libvmod-dns/commit/2fe9bad9a6a6385926fef0eb26b798cd5006917f
https://github.com/nigoroll/libvmod-dns/commit/a6ac7716bb5399b2857d34c90bf2b15c4996829c
https://github.com/nigoroll/libvmod-dns/commit/fb2d9a631ae0824d6d10fe1a23ce5db9bcc508d5

**Comment by Dridi** [comment]
Here comes the feedback:

> https://github.com/nigoroll/libvmod-dns/commit/2fe9bad9a6a6385926fef0eb26b798cd5006917f

Good catch, fixed!

> https://github.com/nigoroll/libvmod-dns/commit/a6ac7716bb5399b2857d34c90bf2b15c4996829c

I'm not happy with doing anything like that because it's a catch 22. We can't rely on `pkg-config` at bootstrap time because we have no guarantee whether `pkg-config` should be run from the PATH (and not just `pkg-config`, it could be a different implementation like `pkgconf`). The `$PKG_CONFIG` program could either be set via an environment variable or a positional argument to the `configure` script and if we want to do it right we need to duplicate the `configure` logic and frankly I still see this as a can of worms.

So I'm planning to generate a `README.rst` file that end-users can fill with project-specific material, where build instructions are already present. And in addition, in the absence of an `ACLOCAL_PATH` export it to `/usr/local/share/aclocal` because 1) `/usr/local` is the default `configure` prefix and 2) that's where *BSD ports and packages are installed by default (at least I'm pretty sure that's the case for FreeBSD).

> https://github.com/nigoroll/libvmod-dns/commit/fb2d9a631ae0824d6d10fe1a23ce5db9bcc508d5

Good catch, and I will give it more thought as we may also want to do the same for the `vcl_path`.

**Comment by nigoroll** [comment]
I don't understand the comment on https://github.com/nigoroll/libvmod-dns/commit/a6ac7716bb5399b2857d34c90bf2b15c4996829c
Yes, we should check for $PKG_CONFIG.

**Comment by nigoroll** [comment]
sorry, close/reopen was an accident

**Comment by nigoroll** [comment]
These issues are addressed in #4 and a071926546f1b1635684b987e27f6b6c3cfb39b8
Regarding the second issue, @Dridi and me got slightly differing opinions, but setting `ACLOCAL_PATH` works and I respect his point.
